apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchonete-api
  template:
    metadata:
      labels:
        app: lanchonete-api
    spec:
      containers:
        - name: lanchonete-api
          image: {{ .Values.api.repository }}:{{ .Values.api.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: DB_USER
              value: {{ .Values.nodeEnv.DB_USER }}
            - name: DB_PASSWORD
              value: {{ .Values.nodeEnv.DB_PASSWORD }}
            - name: DB_NAME
              value: {{ .Values.nodeEnv.DB_NAME }}
            - name: DB_HOST
              value: {{ .Values.nodeEnv.DB_HOST }}
            - name: DB_PORT
              value: "{{ .Values.nodeEnv.DB_PORT }}"
            - name: PORT
              value: "{{ .Values.nodeEnv.PORT }}"
