api:
  repository: rafaelvmasc/lanchonete-api
  tag: 2.0.0
  pullPolicy: IfNotPresent
  domain: yeee.app
  subdomain: lanchonete
  service:
    type: ClusterIP
    port: 3000
  env:
    DB_PORT: 5432
    PORT: 3000
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
